# permissions for end users to edit ploigosplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ploigosplatform-editor-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - ploigosplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - ploigosplatforms/status
  verbs:
  - get
