---

subdomain: '{{ full_cluster_name }}'

redhat_gov_catalog_tag: "latest"

jenkins_repository_name: openshift-release-dev

crw_admin_user:
  username: codeready-admin
  password: demo123

platform_tls_verify: "{{ tssc_platform.tls.verify | default(true) }}"
platform_trust_bundle_config_map: "{{ tssc_platform.tls.trust_bundle_config_map | default(omit) }}"

# rhsso and gitea need to be first for others to succeed
managed_services: "{{ (['rhsso', tssc_platform.services.source_control.name] + tssc_platform.services.values() | list | json_query('[?managed].name')) | unique }}"
