apiVersion: redhatgov.io/v1alpha1
kind: PloigosPlatform
metadata:
  name: ploigosplatform-testing
spec:
  ploigosPlatform:
    services:
      continuousIntegration:
        name: jenkins
      sourceControl:
        name: gitea
      artifactRepository:
        name: nexus
      staticCodeAnalysis:
        name: sonarqube
      continuousDeployment:
        name: argocd
      uat:
        name: selenium
      containerRegistry:
        name: nexus
