apiVersion: redhatgov.io/v1alpha1
kind: TsscPlatform
metadata:
  name: tsscplatform-jenkins-private
spec:
  tsscPlatform:
    services:
      continuousIntegration:
        name: jenkins
      sourceControl:
        name: gitea
      artifactRepository:
        name: nexus
      staticCodeAnalysis:
        name: sonarqube
      continuousDeployment:
        name: argocd
      uat:
        name: selenium
      containerRegistry:
        name: nexus
    tls:
      verify: false
      trustBundleConfigMap: trustedcabundle
