apiVersion: redhatgov.io/v1alpha1
kind: PloigosPlatform
metadata:
  name: ploigosplatform-tekton
spec:
  ploigosPlatform:
    services:
      continuousIntegration:
        managedService: tekton
      sourceControl:
        managedService: gitea
      artifactRepository:
        managedService: nexus
      staticCodeAnalysis:
        managedService: sonarqube
      continuousDeployment:
        managedService: argocd
      uat:
        managedService: selenium
      containerRegistry:
        managedService: nexus
      sso:
        managedService: rhsso
