apiVersion: redhatgov.io/v1alpha1
kind: TsscPlatform
metadata:
  name: tsscplatform-jenkins-private
spec:
  tsscPlatform:
    providers:
      ciTool: jenkins
      containerRegistry: nexus
    tls:
      verify: false
      trustBundleConfigMap: trustedcabundle
