apiVersion: redhatgov.io/v1alpha1
kind: TsscPipeline
metadata:
  name: tsscpipeline-tekton
spec:
  appName: ref-quarkus-mvn-tekton-std
  serviceName: fruit
  appRepo:
    sourceUrl: http://gitea.tssc.rht-set.com/akrohg/reference-quarkus-mvn_tekton_workflow-standard.git
    destinationRepoName: reference-quarkus-mvn_tekton_workflow-standard
  helmRepo:
    sourceUrl: http://gitea.tssc.rht-set.com/akrohg/reference-quarkus-mvn-cloud-resources_tekton_workflow-standard.git
    destinationRepoName: reference-quarkus-mvn-cloud-resources_tekton_workflow-standard
  autoStartPipeline: true
