apiVersion: redhatgov.io/v1alpha1
kind: TsscPipeline
metadata:
  name: tsscpipeline-testing
spec:
  appName: ref-quarkus-mvn-jenkins-std
  serviceName: fruit
  appRepo:
    sourceUrl: http://gitea.tssc.rht-set.com/akrohg/reference-quarkus-mvn_jenkins_workflow-standard.git
    destinationRepoName: reference-quarkus-mvn_jenkins_workflow-standard
  helmRepo:
    sourceUrl: http://gitea.tssc.rht-set.com/akrohg/reference-quarkus-mvn-cloud-resources_jenkins_workflow-standard.git
    destinationRepoName: reference-quarkus-mvn-cloud-resources_jenkins_workflow-standard
  autoStartPipeline: true
