- name: Wait for Nexus to respond to requests
  uri:
    url: '{{ nexus_url }}/repository/maven-releases/'
    validate_certs: no
  register: _nexus_endpoint
  until: _nexus_endpoint.status == 200
  retries: 30
  delay: 5

- name: Create ploigos Service Account
  shell: >
    devsecops-api nexus add-user
    {{ nexus_url }}
    --login-username {{ nexus_username }} --login-password {{ nexus_password }}
    --usernames "{{ ploigos_service_account.username }}"
    --passwords "{{ ploigos_service_account.password }}"

- name: Change the settings on the maven-releases repo to allow artifacts to be overwritten
  shell: >-
    devsecops-api nexus update-repository
    {{ nexus_url }}
    --login-username '{{ nexus_username }}' --login-password '{{ nexus_password }}'
    --repository-names 'maven-releases'
    --write-policy 'ALLOW'
  register: updated_nexus_repos
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: updated_nexus_repos.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: updated_nexus_repos.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or updated_nexus_repos.rc != 0

- name: Add raw repositories
  shell: >-
    devsecops-api nexus add-raw-repository
    {{ nexus_url }}
    --login-username '{{ nexus_username }}' --login-password '{{ nexus_password }}'
    --repository-names '{{ item }}'
  register: signatures_repo
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: signatures_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: signatures_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or signatures_repo.rc != 0
  loop:
  - container-image-signatures
  - result-artifacts-archive
  - workflow-evidence

- name: Create docker repository if using nexus as container registry
  shell: >-
    devsecops-api nexus add-docker-repository
    {{ nexus_url }}
    --login-username '{{ nexus_username }}' --login-password '{{ nexus_password }}'
    --repository-names docker-hosted
  register: docker_repo
  changed_when: docker_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
  failed_when: docker_repo.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` failed`)]")|length > 0 or docker_repo.rc != 0
  when: nexus_docker_enabled