- name: Create ploigos-container-builder SCC and role
  k8s:
    definition: "{{ lookup('template', 'container-builder.yml.j2') | from_yaml }}"

- name: Complete Jenkins tasks, if enabled
  block:
  - name: Create a Jenkins instance
    k8s:
      namespace: '{{ ploigos_namespace }}'
      definition: '{{ lookup("template", "jenkins.yml.j2")|from_yaml }}'
      state: '{{ cr_state }}'

  - name: Create RoleBinding for use by jenkins
    k8s:
      definition: "{{ lookup('template', 'jenkins-rolebinding.yml.j2') | from_yaml }}"
  when: "'jenkins' in managed_services"

# Operator-backed services
- name: Get a list of operator groups
  k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: '{{ ploigos_namespace }}'
  register: operator_groups

- set_fact:
    operator_group_name: '{{ operator_groups.resources[0].metadata.name }}'
  when: operator_groups.resources

- name: Ensure OperatorGroup exists
  k8s:
    definition: '{{ lookup("template", "operator-group.yml.j2") }}'

- name: 'Create Subscriptions'
  k8s:
    definition: '{{ lookup("template", "subscriptions/" + operator_app + ".yml.j2") }}'
  loop: '{{ managed_services }}'
  loop_control:
    loop_var: operator_app
    label: operator_app
  when: lookup("template", "subscriptions/" + operator_app + ".yml.j2", errors='ignore')

- name: 'Apply CustomResources'
  k8s:
    definition: '{{ lookup("template", "custom-resources/" + operator_app + ".yml.j2") }}'
  register: deployment
  until: not deployment.failed
  retries: 5
  delay: 10
  loop: '{{ managed_services }}'
  loop_control:
    loop_var: operator_app
    label: operator_app
  when: lookup("template", "custom-resources/" + operator_app + ".yml.j2", errors='ignore')
