---
- name: Clean up resources
  shell: |
    oc delete -n {{ tssc_namespace }} KeycloakUser,KeycloakClient,KeycloakRealm --all || true
    oc delete -n {{ tssc_namespace }} all,configmap,pvc,serviceaccount,rolebinding -l app=jenkins-persistent || true
    oc delete -n {{ tssc_namespace }} secret gitea-access-token || true
