- hosts: localhost
  vars:
    ploigos_platform:
      services:
        continuous_integration:
          external_service:
            jenkins:
              url: bleh
              token: bleh
        container_registry:
          external_service:
            nexus:
              url: bleh
              token: bleh
    managed_services: 
    - sso
    - gitea
  tasks:
  - set_fact:
      all_services: "{{ ploigos_platform.services.values() | list | json_query('[?external_service].external_service') | json_query('[].{key:keys(@)[0], value:values(@)[0]}') | items2dict }}"
      source_control:
        gitea:
          url: hey
          token: hey

  - set_fact: 
      all_services: "{{ all_services | combine(source_control) | list }}"

 