name: Run Operator SDK tests, release new operator images if tests succeed

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.adoc'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.adoc'

jobs:
  release:
    needs: [test-cluster]
    if: >
      github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build, bundle, and push
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          pip3 install --user --upgrade setuptools wheel pip
          hack/operate.sh --push-images --bundle --extra-tag=latest --verbose --formatter
