---
- name: Get Gitea Pod
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ ploigos_namespace }}'
    label_selectors:
    - app=gitea
  register: gitea_pod

- name: Create RHSSO Client definition for Gitea
  k8s:
    definition: '{{ lookup("template", "rhsso-gitea-client.yml.j2")|from_yaml }}'
  register: rhsso_client

- name: Wait for Gitea KeycloakClient to reconcile
  k8s_info:
    api_version: keycloak.org/v1alpha1
    kind: KeycloakClient
    name: gitea-client
    namespace: "{{ rhsso_project_name }}"
  register: gitea_kc
  until:
    - gitea_kc.resources|length > 0
    - gitea_kc.resources[0].status is defined
    - gitea_kc.resources[0].status['ready']
  delay: 10
  retries: 6

- name: Wait for client secret to be created
  k8s_info:
    api_version: v1
    kind: Secret
    name: keycloak-client-secret-gitea
    namespace: "{{ rhsso_project_name }}"
  register: gitea_secret
  until:
    - "gitea_secret.resources[0].data['CLIENT_SECRET'] != ''"
  retries: 12
  delay: 5

- name: Fetch Gitea secret for RHSSO
  set_fact:
    rhsso_gitea_secret: "{{ gitea_secret.resources[0].data['CLIENT_SECRET'] | b64decode }}"

# TODO: this should all be part of the Gitea operator
# unfortunately, when we move to Secret-based client secrets we cannot
# easily know when the Secret has changed, so updating an existing client secret
# is difficult. Plus, Gitea CLI doesn't provide a means to check that no
# changes were made to OAuth config - all update commands will cause an UPDATE
# query regardless.
- name: Configure RHSSO as an OAuth2 provider for Gitea
  shell: |
    oc='{{ oc_cli }}'
    pod=$($oc get pods -n {{ gitea_project_name }} -l {{ gitea_pod_label }} -o jsonpath='{.items[0].metadata.name}')
    gitea="$oc exec $pod -n {{ gitea_project_name }} -- /home/gitea/gitea --config=/home/gitea/conf/app.ini"
    $gitea admin auth list |& grep -F rhsso
    if [ $? -gt 0 ]; then
      output=$($gitea admin auth add-oauth --name=rhsso --provider openidConnect --key {{ rhsso_gitea_client_id }} --secret {{ rhsso_gitea_secret }} --auto-discover-url  https://keycloak-{{ rhsso_project_name }}.apps.{{ subdomain }}/auth/realms/{{ rhsso_realm_name }}/.well-known/openid-configuration 2>&1)
      if echo "$output" | grep -qF 'login source already exists'; then
          echo ok
      elif echo "$output" | grep -qF 'Failed to run app'; then
          echo failed
      elif echo "$output" | grep -qE 'INSERT INTO "login_source"'; then
          echo changed
      else
          echo failed
      fi
    else
      echo ok
    fi
  register: gitea_rhsso_oauth
  changed_when: '"changed" in gitea_rhsso_oauth.stdout_lines'
  failed_when: '"failed" in gitea_rhsso_oauth.stdout_lines'

- name: Restart gitea if the RHSSO changes were applied
  block:
  - name: Kill gitea pod for auth changes to take into effect
    k8s:
      api_version: v1
      kind: Pod
      namespace: '{{ gitea_project_name }}'
      name: "{{ (gitea_pod.resources|first).metadata.name }}"
      state: absent
      wait: true

  - name: Wait **again** for Gitea to finish being created with RHSSO settings
    k8s_info:
      api_version: v1
      kind: Pod
      namespace: '{{ gitea_project_name }}'
      label_selectors:
      - "{{ gitea_pod_label }}"
    register: gitea_pod
    until: gitea_pod.resources|length > 0 and (gitea_pod.resources|first).status.phase == "Running"
    retries: 10
    delay: 30
  when: gitea_rhsso_oauth.changed
