- set_fact:
    sso_services: "{{ supported_services | intersect(managed_services) }}"
  vars:
    supported_services:
    - gitea
    - quay
    - sonarqube
    - argocd

- name: Deploy OpenShift Realm
  k8s:
    definition: "{{ lookup('template', 'realm.yml.j2') }}"

- name: Configure platform services
  include_tasks: '{{ _sso_service }}.yml'
  loop: "{{ sso_services }}"
  loop_control:
    loop_var: _sso_service
